config/routes.rb
Mistalks::Application.routes.draw do
  resources :posts

  root 'welcome#index'

  get 'about' => 'welcome#about'
  get 'contact' => 'welcome#contact'

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  validate :title, :value, presence: true

  def humanize_date
    created_at.strftime('%d.%m')
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  include Clearance::User

  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_filter :authorize, except: [:index, :show]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.paginate(:page => params[:page], :per_page => 5).order('created_at DESC')
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
    unless current_user.posts.where(id: params[:id]).present?
      respond_to do |format|
        format.html { redirect_to posts_path, flash: {warning: 'Cant touch this post.'} }
      end
    end
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = current_user.posts.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render action: 'show', status: :created, location: @post }
      else
        format.html { render action: 'new' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :value)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    redirect_to :posts
  end

  def about
    
  end

  def contact
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def nav_link(link_text, link_path)
    class_name = current_page?(link_path) ? 'active' : ''

    content_tag(:li, :class => class_name) do
      link_to link_text, link_path
    end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
  def markdown(text)
    @markdown ||= Redcarpet::Markdown.new(Redcarpet::Render::HTML, hard_wrap: true, 
      filter_html: true, autolink: true,no_intraemphasis: true,fenced_code: true,gh_blockcode: true)
    @markdown.render text
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mistalks</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="">
  <meta name="author" content="">
  <!-- <link rel="shortcut icon" href="../../assets/ico/favicon.png"> -->
  <link href='http://fonts.googleapis.com/css?family=Oxygen&subset=latin,latin-ext' rel='stylesheet' type='text/css'>

  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <!-- Fixed navbar -->
  <nav class="navbar navbar-default navbar-fixed-top navy" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">mis.talks</a>
      </div>
      <div class="navbar-collapse collapse navy-collapse">
        <ul class="nav navbar-nav navbar-right">
          <%= nav_link '.talks', posts_path %>
          <%= nav_link '.about', about_path %>
          <%= nav_link '.contact', contact_path %>
        </ul>
      </div><!--/.nav-collapse -->
    </div>
  </nav>
  <!-- End Fixed navbar -->

  <!-- begin container -->
  <div class="container">
    <!-- flash notice -->
    <div id="flash">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>">
          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
          <%= value %>
        </div>
      <% end %>
    </div>
    <!-- End flash notice -->

    <%= yield %>
  </div>
  <!-- end container -->

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <!-- <%= f.label :title %><br> -->
    <%= f.text_field :title, placeholder: 'Title', class: "form-control" %> <br>
  </div>
  <div class="field">
    <%= f.text_area :value, placeholder: 'Your post', class: "form-control", id: 'editor' %>
  </div>

  <div class="actions">
    <%= f.submit 'Save', class: "btn btn-default btn-block btn-lg" %>
  </div>
<% end %>

<script>
  var editor = new Editor();
  editor.render();
</script>

app/views/posts/_post.html.erb
<div class="post">
  <div class="title">
    <small class='badge title-date'><%= post.humanize_date%></small>
    <h1>
      <%= link_to(post_path(post), html_options = {}) do
        "# #{post.title}"
      end %>
    </h1>
  </div>
  <hr />
  <%=raw markdown post.value %>
</div>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

app/views/posts/index.html.erb
<% if signed_in? %>
  Signed in as: <%= current_user.email %>
  <%= link_to 'Sign out', sign_out_path, :method => :delete %>
<% else %>
  <%= link_to 'Sign in', sign_in_path %>
<% end %>

<% @posts.each do |post| %>
  <%= render partial: 'post', locals: {post: post} %>
<% end %>

<%= will_paginate @posts, renderer: BootstrapPagination::Rails%>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>
<%= render partial: 'post', locals: {post: @post} %>

app/views/welcome/about.html.erb
about page

app/views/welcome/contact.html.erb
contact

app/views/welcome/index.html.erb
Hi